name: Release
on:
  pull_request:
    types:
      - closed
jobs:
  create-release:
    permissions:
      contents: write
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: .github/workflows/Gemfile
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - run: bundle
      - name: download artifacts and create release
        id: download_artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "bundle exec ruby .github/workflows/fetch_release.rb"
