name: Release
on:
  pull_request:
    types:
      - closed
jobs:
  create-release:
    permissions:
      contents: write
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts and create release
        id: download_artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "ruby .github/workflows/fetch_release.rb"
